#!/bin/bash
NTHREADS=24
if [[ -z "${NTHREADS}" ]]; then NTHREADS=1; fi
NTHREADS=24

TBENCH_QPS=1000 TBENCH_MAXREQS=0 TBENCH_WARMUPREQS=1 \
    TBENCH_MINSLEEPNS=100000 ./mttest_integrated -j${NTHREADS} mycsba masstree
